### ISSUE TITLE
zort?

### ISSUE THREAD

**Issue by Bes-js** [aresxrd/jaylenozi-v14-bots#1]
e

**Comment by Bes-js** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/2e58f32e-7fa5-4e59-a581-7773966ffe5b

**Comment by Bes-js** [comment]
![image (22)](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/bb577ddf-4640-43ef-b32b-c17f1fef0a89)

**Comment by Bes-js** [comment]
![IMG_2964](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/a083052d-22bc-4088-8c7d-fe0e37392383)

**Comment by Bes-js** [comment]
![photo_2024-01-22_06-18-33](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/ab5c8b31-0c9a-4bae-a9bf-d1c1baa0aeb0)

**Comment by Bes-js** [comment]
![1069938786538106891](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/40b96974-d179-4b3f-ac36-fa5162a02b53)

**Comment by Bes-js** [comment]
Uploading c3b9cec2e92a6f11e70d185ac25eb882.mp4…

**Comment by Bes-js** [comment]
![997526-1439101780](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/524b6e4a-a037-420c-ab00-d6db7560937c)

**Comment by Bes-js** [comment]
![a9f973d0-8848-4982-98e5-9f3c80c8c098](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/dcf45c5c-c801-4dea-ab82-d1a0dc173b64)

**Comment by Bes-js** [comment]
![a_e7043b70688fcb33522faf807d51c18a-2](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/32a06c74-5200-4277-b9ef-ed2efadb573a)

**Comment by ertucuk** [comment]
ELĞŞÇQWĞÜŞEĞŞQWDLPĞQWLPĞŞÜDĞÜŞQWDĞÜŞWQĞÜŞDWQÜŞDĞŞQWĞDŞQWDŞÜQWĞDQWDQWDQWDQWDQWDLPĞQWPDLĞQWPŞDĞQWÜŞDŞQW

**Comment by Bes-js** [comment]
![image_750x_606380e1db5a4](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/41f5cc2d-3d29-4801-aec2-a3587df56849)

**Comment by Bes-js** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/3f8c1728-433b-4061-98d9-fc465e62ef94

**Comment by Bes-js** [comment]
![Ey7dm3bWYAMXeup](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/0391953c-7c01-4bb9-a2b6-be54b4bf8cb9)

**Comment by vante-dev** [comment]
sil lan bu repoyu babanı ararım senin

**Comment by Bes-js** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/5643ec32-333f-4acd-aa76-d6905dc1c0db

**Comment by ertucuk** [comment]
Uploading C24712F9B1E7B215152F113612C42AAB_video_dashinit.mp4…

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-04 220048](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/f1bead9c-6546-461b-8dc9-2c85627aed66)

**Comment by ertucuk** [comment]
![c04283aa23bad66f41bbce1928f32654](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/c083d1df-80ae-4c6c-912e-1c9644778cf2)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-12-16 152318](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/8553d27f-b12a-447e-a501-669a8301060c)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-07-14 221803](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/6a1cb172-0c8a-49b3-88c6-cd9f5f81d7f9)

**Comment by ertucuk** [comment]
![sasas](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/62816c46-55e1-4fe8-a442-a3e35f41c221)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-10-20 061038](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/3b350ec4-a12d-4c28-b4b6-1c03fb6c1ed7)

**Comment by ertucuk** [comment]
![Capture](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/1d573a3d-626d-41d5-a197-b44a95ac99b6)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-28 230752](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/2bcfde12-348b-4609-91cc-fa557695c404)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-09-27 233033](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/87004edb-c96e-434a-bd33-a4a6a7dd27c9)

**Comment by ertucuk** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/960c62ce-31b6-4e80-b53b-2fc14fc55c82

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-07-22 233653](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/e0c42bd7-a0e9-4554-9998-b0c869fd9e66)

**Comment by ertucuk** [comment]
![recepbaltas](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/5a15aff9-478a-4632-898f-5488d2f8064a)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-07-23 061346](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/8bb88a93-00d0-4204-b635-8896e3ce26c9)

**Comment by ertucuk** [comment]
![utkussssss](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/e784df1d-92c8-4c7a-9cf6-c04a9a12507c)

**Comment by ertucuk** [comment]
![e7051df7d0cdb8dae1a4d0ce94bc5ad8](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/494a116d-33b2-4953-8930-34fde1889e57)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-10-25 191730](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/3e2e06db-7af9-46b8-b50d-b44f4437333b)

**Comment by ertucuk** [comment]
![discord-avatar-128-D8UEQ](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/43e0ee38-89e7-455d-97b2-aea8a0baf167)

**Comment by pikushe** [comment]
Uploading SPOILER_be972d8f47313e014fce5fb474e813b9.mp4…

**Comment by Bes-js** [comment]
![Uploading Ekran görüntüsü 2024-01-14 134044.png…]()

**Comment by ertucuk** [comment]
![b97f4582a20b1e9988aff4ad6942238c](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/d24a9d43-f24b-495b-9ad3-fa99b569ac69)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-01 235637](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/403b1f18-37b7-4d1f-8f89-87057166e107)

**Comment by ertucuk** [comment]
![image (3)](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/097af0df-f308-44d3-b163-b6433162badf)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/9e6ddf2f-c097-427b-814b-754f7d5ab21e

**Comment by vante-dev** [comment]
GRRRRRRRRR PAAOWWW

**Comment by ertucuk** [comment]
![Mys-canvas](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/05c1b15c-997c-4341-99ec-c7f0546fb08b)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/12302b37-0d6a-45f0-9a1e-c44c9389159f

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-07-25 033138](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/d08f3e9c-4745-4b59-b0d8-d820076477ed)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-06 184834](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/bd77abd9-5620-418d-bdba-c04394bfd25d)

**Comment by ertucuk** [comment]
![ertu3](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/348364ce-479c-444f-a7a5-b56c9f8e1ab3)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/227f3330-96b4-4974-b642-cebf1b677b1b

**Comment by ertucuk** [comment]
![IMG-20230808-WA0009](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/e918e489-09a5-40a6-b4f8-ecee7746fb86)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/700e375f-3bbf-4a0b-b499-53eccf7807d6

**Comment by ertucuk** [comment]
![IMG_2622](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/529bc15b-3346-4be0-998f-312324aac7f3)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/5a7c0596-525d-4665-9b49-7cb94135a73c

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-12-06 101127](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/b1656f1b-e58b-4f85-9278-132fb335a3ff)

**Comment by ertucuk** [comment]
![1e569ac9fbb2f3f767e87a6fcbc9dc52](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/5a6f7728-7525-480d-b36e-f20c7780a97c)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-18 022714](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/12e5a508-7cce-47da-b3fc-470631eb8aea)

**Comment by ertucuk** [comment]
![image (2)](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/b72b904f-39d3-4e5b-bd30-0adf28c1d776)

**Comment by pikushe** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/89347562/ff758520-83ca-4bdc-be6b-83937040997a

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-11-22 004258](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/c1ef062e-c398-42ee-b02d-477cfbb3d5c1)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-07-20 184626](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/7fd44f16-3cf1-427c-9295-6d0b3ccb2b6d)

**Comment by ertucuk** [comment]
![image 1](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/395af1b8-0a94-4529-aa21-81ae207699d2)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-12-18 194045](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/b25d6edf-7e93-48bc-b6fb-bd59577d9613)

**Comment by ertucuk** [comment]
![bcaacc15336ceae1fd723f51ddfa8af4 1](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/1ae9c17c-da6f-493f-981b-a1123be08624)

**Comment by ertucuk** [comment]
![Ekran_goruntusu_2024-01-20_173844 1](https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/899a900e-dc60-442d-9795-400df378a7e1)

**Comment by Bes-js** [comment]
![2020-10-21_09-53-40](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/2b30bc66-ab42-43f9-9fa2-be66ad645c0d)

**Comment by ertucuk** [comment]
<img width="457" alt="image 1" src="https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/d55a86ee-0136-46af-ade2-d6e0daa7b407">

**Comment by Bes-js** [comment]
![2023-03-08_22-45-14](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/7d5655f1-8550-4af6-8a96-d682eb2cfb52)

**Comment by Bes-js** [comment]
![2023-06-07_18-14-19](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/e131474a-31af-4e77-ba44-e7fa1e66a1d0)

**Comment by Bes-js** [comment]
![2023-06-18_00-30-00](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/35964f96-4179-47b6-abc7-1123fa5cd0bf)
![2023-06-18_00-30-33](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/424b42b9-5e7f-4691-a4b7-04b1659130bd)

**Comment by ertucuk** [comment]
<img width="181" alt="313123121" src="https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/f3b0b417-7de9-4d15-bbb0-0c05f87dbb50">

**Comment by Bes-js** [comment]
![2023-11-02_00-04-51](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/4060fad4-9e5f-436c-a104-f6c376c91cc3)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2023-08-05 172523](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/6b10ea7b-4247-484a-85f0-aa6a01ca2a48)

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-21 125730](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/bf73c1e4-a76b-4d5f-aec2-b45dbd7c2e29)

**Comment by ertucuk** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/d0facd88-7a48-4d49-9198-87b027d00243

**Comment by Bes-js** [comment]
![Ekran görüntüsü 2024-01-18 232502](https://github.com/aresxrd/jaylenozi-v14-bots/assets/89789101/2637b838-7577-47ce-ab52-e9fda16ed4c8)

**Comment by ertucuk** [comment]
https://github.com/aresxrd/jaylenozi-v14-bots/assets/68440024/ab4a4300-5611-4379-adb2-e3fe975ce828
